### ISSUE TITLE
AutoGo没找到

### ISSUE THREAD

**Issue by ChenglinZhang777** [TellH/AutoGo#1]

**Comment by TellH** [comment]
@chiely 添加依赖了吗

**Comment by ChenglinZhang777** [comment]
![image](https://cloud.githubusercontent.com/assets/3701564/17483447/a259e804-5db8-11e6-8fdc-8fccdfd86a53.png)
以上是源码demo上引用的包路径

![image](https://cloud.githubusercontent.com/assets/3701564/17483414/807bb492-5db8-11e6-8ecf-340aca2f70ab.png)
以上是我本地引用的依赖库class文件

**Comment by TellH** [comment]
AutoGo.java是编译期在app Module的build apt目录上自动生成的类，不属于核心库的类

**Comment by ChenglinZhang777** [comment]
恩，我项目的依赖是：
`classpath 'com.android.tools.build:gradle:2.2.0-alpha7'`
模块annotation依赖是：
`annotationProcessor 'com.tellh:autogo-core:1.0.3'`

没能正确生成AutoGo，不过butterknife和barber都能生成对应的文件，我再看看...

**Comment by ChenglinZhang777** [comment]
额，我的core写错了

**Comment by ChenglinZhang777** [comment]
给你添麻烦了
