### ISSUE TITLE
How about adding a goForResult Method?

### ISSUE THREAD

**Issue by registernet** [TellH/AutoGo#3]
How about adding a new method to the interface AutoLauncher like this:
public interface AutoLauncher {
    void go();
    void goForResult(int requestCode);
}
generated implementation:
public class xxx implements AutoLauncher{
    // method as usual
    // then
    @Override
    public void goForResult(int requestCode) {
         srcActivity.startActivityForResult(intent, requestCode);
         intent = null;
         srcActivity = null;
    }
}
Usage:
AutoGo.from(xxx).xxx.goForResult(requestCode);
For the case of startActivityForResult(Intent intent, int requestCode) ?

**Comment by registernet** [comment]
MethodSpec goForResult = MethodSpec.methodBuilder("goForResult")
            .addModifiers(Modifier.PUBLIC)
            .addAnnotation(Override.class)
            .returns(TypeName.VOID)
            .addParameter(TypeName.INT, "requestCode")
            .addStatement("srcActivity.startActivityForResult(intent, requestCode)")
            .addStatement("intent = null")
            .addStatement("srcActivity = null")
            .build();

**Comment by TellH** [comment]
This is so nice idea! Thanks for your contribution, I will work for it as soon as possible.

**Comment by registernet** [comment]
Thanks a lot!

**Comment by TellH** [comment]
Thanks @registernet , this featrue is available in the new version.
